### ISSUE TITLE
Remove Database Connection and use DBConnection.java in StatusNotes.java

### ISSUE THREAD

**Issue by ramtinnikbakht** [CST316FAF/cmsproject#46]
Remove Database Connection on line: 186-205 and instead use the DBConnection.java in StatusNotes.java whenever connecting to the database.

**Comment by eallam** [comment]
Iam going to fix it, and make sure.

**Comment by ramtinnikbakht** [comment]
Resolved Issue. Git Commit #: e7186ea770a8e9bc12ea005ae9ac0bd6b5351efb
